version: '3.7'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
        container_name: elastic-search
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - mynetwork

    log-exploration:
        image: quay.io/openshift-logging/log-exploration-api:1f47f6b
        container_name: log-exploration
        networks: 
            - mynetwork
        ports:
            - 8080:8080
        environment:
            - ES_ADDR=http://elasticsearch:9200 
            - ES_TLS=false
        depends_on: 
            - "elasticsearch"
networks: 
    mynetwork: {}